name: Deploy docs to Cloudflare Pages

on:
  push:
    branches:
      - 'master'
    paths:
      - 'howto/**'
  pull_request:
    branches:
      - 'master'
    paths:
      - 'howto/**'

jobs:
  deploy:
    defaults:
      run:
        working-directory: ./howto
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup mdBook
        env:
          MDBOOK_VERSION: v0.4.23
          MDBOOK_MERMAID_VERSION: v0.12.6
        run: |
          mkdir -p bin
          wget -qO- \
            https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdbook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | \
            tar -xvz --directory=bin
          wget -qO- \
            https://github.com/badboy/mdbook-mermaid/releases/download/${MDBOOK_MERMAID_VERSION}/mdbook-mermaid-${MDBOOK_MERMAID_VERSION}-x86_64-unknown-linux-gnu.tar.gz | \
            tar -xvz --directory=bin
          echo "${PWD}/bin" >> $GITHUB_PATH
      - name: Build
        run: mdbook build
